"""Add Stripe ID to User

Revision ID: 2b9a22ea33dc
Revises: a8b5cdea47fe
Create Date: 2025-07-21 15:38:26.843286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b9a22ea33dc'
down_revision = 'a8b5cdea47fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_stripe_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('recipient_stripe_id')

    # ### end Alembic commands ###
