"""Add visibility to posts

Revision ID: 4f29cc1737d5
Revises: 8ffa937991f2
Create Date: 2025-05-20 13:46:58.886331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f29cc1737d5'
down_revision = '8ffa937991f2'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visibility', sa.String(length=20), nullable=False, server_default='public'))
        batch_op.alter_column('visibility', server_default=None)



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('visibility')

    # ### end Alembic commands ###
