"""Add PostReport model

Revision ID: 529e4e885f41
Revises: cf0488220ddf
Create Date: 2025-05-20 18:34:24.566017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '529e4e885f41'
down_revision = 'cf0488220ddf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_reports',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.post_id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_reports')
    # ### end Alembic commands ###
