"""Cleaned up routes.py & added new routes to support increased functionality

Revision ID: 52dc7775feca
Revises: 06f067db6865
Create Date: 2025-08-08 16:06:06.871406

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '52dc7775feca'
down_revision = '06f067db6865'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.chapter_id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.school_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('school_bans')
    op.drop_table('chapter_bans')
    with op.batch_alter_table('chapter_join_requests', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('chapter_join_requests_decided_by_fkey'), type_='foreignkey')
        batch_op.drop_column('decided_by')

    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.alter_column('stripe_session_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)

    with op.batch_alter_table('school_join_requests', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('school_join_requests_decided_by_fkey'), type_='foreignkey')
        batch_op.drop_column('decided_by')

    with op.batch_alter_table('school_memberships', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school_memberships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))

    with op.batch_alter_table('school_join_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('decided_by', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('school_join_requests_decided_by_fkey'), 'users', ['decided_by'], ['user_id'])

    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('stripe_session_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('chapter_join_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('decided_by', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('chapter_join_requests_decided_by_fkey'), 'users', ['decided_by'], ['user_id'])

    op.create_table('chapter_bans',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('chapter_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.chapter_id'], name=op.f('chapter_bans_chapter_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('chapter_bans_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('chapter_bans_pkey')),
    sa.UniqueConstraint('user_id', 'chapter_id', name=op.f('uq_chapter_ban_once'))
    )
    op.create_table('school_bans',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('school_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.school_id'], name=op.f('school_bans_school_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('school_bans_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('school_bans_pkey')),
    sa.UniqueConstraint('user_id', 'school_id', name=op.f('uq_school_ban_once'))
    )
    op.drop_table('bans')
    # ### end Alembic commands ###
