"""Add purchased_at to Purchase model

Revision ID: 5bf21e5533af
Revises: 5b943999e047
Create Date: 2025-07-22 14:59:45.205751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bf21e5533af'
down_revision = '5b943999e047'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchased_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_column('purchased_at')

    # ### end Alembic commands ###
