"""Add stripe_account_id to User

Revision ID: afc9e72cb648
Revises: 2b9a22ea33dc
Create Date: 2025-07-21 17:52:12.898996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afc9e72cb648'
down_revision = '2b9a22ea33dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_account_id', sa.String(length=128), nullable=True))
        batch_op.drop_column('recipient_stripe_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_stripe_id', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('stripe_account_id')

    # ### end Alembic commands ###
