"""Add views column to posts with default 0

Revision ID: c034825868b3
Revises: 610b17205cd9
Create Date: 2025-05-19 20:53:18.841614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c034825868b3'
down_revision = '610b17205cd9'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('posts') as batch_op:
        batch_op.add_column(sa.Column('views', sa.Integer(), nullable=True, server_default='0'))
        batch_op.alter_column('views', nullable=False)



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('views')

    # ### end Alembic commands ###
