"""Add handle and school_id to users

Revision ID: cf0488220ddf
Revises: 4f29cc1737d5
Create Date: 2025-05-20 17:46:39.127386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf0488220ddf'
down_revision = '4f29cc1737d5'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('users', schema=None) as batch_op:
        # Step 1: Add nullable handle column (no unique constraint yet)
        batch_op.add_column(sa.Column('handle', sa.String(length=50), nullable=True))

    # Step 2: Populate handle with unique values
    op.execute("""
        UPDATE users
        SET handle = 'temp_handle_' || user_id
    """)

    # Step 3: Make handle NOT NULL and UNIQUE
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('handle', nullable=False)
        batch_op.create_unique_constraint(None, ['handle'])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('handle')

    # ### end Alembic commands ###
